export const RECEVER_FIXTURES = 'RECEVER_FIXTURES'
export const RECEVER_TOTAL_BETTING = 'RECEVER_TOTAL_BETTING'
export const ACCEPT_BETTING = 'ACCEPT_BETTING'

export const RECEVER_MATCHES = 'RECEVER_MATCHES'

export const INIT_WEB3 = 'INIT_WEB3'
export const RECEVER_WEB3_NETWORK = 'RECEVER_WEB3_NETWORK'
export const RECEVER_WEB3_ACCOUNT = 'RECEVER_WEB3_ACCOUNT'

export const OPEN_DIALOG = 'OPEN_DIALOG'
export const INIT_DATA_DIALOG = 'INIT_DATA_DIALOG'

export const RECEVER_ODDS_FILTER = 'RECEVER_ODDS_FILTER'
export const RECEVER_TOTAL_ODDS = 'RECEVER_TOTAL_ODDS'
export const RECEVER_MY_ODDS = 'RECEVER_MY_ODDS'
export const CANCEL_ODDS = 'CANCEL_ODDS'
export const FILTER_ODDS = 'FILTER_ODDS'

export const INIT_CONTRACT = 'INIT_CONTRACT'
export const CREATE_OFFER = 'CREATE_OFFER'
export const CREATE_DEAL = 'CREATE_DEAL'
export const RECEIVE_MATCHES = 'RECEIVE_MATCHES'

export const NOTIFY_CLEAR = 'NOTIFY_CLEAR'
export const NOTIFY_OPEN  = 'NOTIFY_OPEN'
