import Vue from 'vue'
import {
  Vuetify,
  VApp,
  VNavigationDrawer,
  VFooter,
  VList,
  VBtn,
  VIcon,
  VGrid,
  VTabs,
  VToolbar,
  VCard,
  VDivider,
  VExpansionPanel,
  VDataTable,
  VMenu,
  VTooltip,
  VChip,
  VDialog,
  VProgressLinear,
  VProgressCircular,
  VForm,
  VTextField,
  VSelect,
  VAvatar,
  VSnackbar,
  VJumbotron,
  transitions
} from 'vuetify'
import 'vuetify/src/stylus/app.styl'

Vue.use(Vuetify, {
  components: {
    VApp,
    VNavigationDrawer,
    VFooter,
    VList,
    VBtn,
    VIcon,
    VTabs,
    VGrid,
    VToolbar,
    VCard,
    VDivider,
    VExpansionPanel,
    VDataTable,
    VMenu,
    VTooltip,
    VChip,
    VDialog,
    VProgressLinear,
    VProgressCircular,
    VForm,
    VTextField,
    VSelect,
    VAvatar,
    VSnackbar,
    VJumbotron,
    transitions
  },
  theme: {
    primary: '#ee44aa',
    secondary: '#424242',
    accent: '#82B1FF',
    error: '#FF5252',
    info: '#2196F3',
    success: '#4CAF50',
    warning: '#FFC107'
  },
})
