export var DIALOG_NAME;
(function (DIALOG_NAME) {
    DIALOG_NAME["START_LOADING"] = "START_LOADING";
    DIALOG_NAME["ODDS_CANCEL"] = "ODDS_CANCEL";
    DIALOG_NAME["INSTALL_METAMASK"] = "INSTALL_METAMASK";
    DIALOG_NAME["STORE_BETTING"] = "STORE_BETTING";
    DIALOG_NAME["BETTING_SHARING"] = "BETTING_SHARING";
})(DIALOG_NAME || (DIALOG_NAME = {}));
export var DIALOG_CLOSE;
(function (DIALOG_CLOSE) {
    DIALOG_CLOSE["BETTING_RELOAD"] = "BETTING_RELOAD";
    DIALOG_CLOSE["BETTING_DEAL_RELOAD"] = "BETTING_DEAL_RELOAD";
    DIALOG_CLOSE["ODDS_RELOAD"] = "ODDS_RELOAD";
})(DIALOG_CLOSE || (DIALOG_CLOSE = {}));
//# sourceMappingURL=dialog.js.map