export enum DIALOG_NAME {
  START_LOADING = 'START_LOADING',
  HOW_IT_WORKS = 'HOW_IT_WORKS',
  ODDS_CANCEL = 'ODDS_CANCEL',
  INSTALL_METAMASK = 'INSTALL_METAMASK',
  STORE_BETTING = 'STORE_BETTING',
  BETTING_SHARING = 'BETTING_SHARING'
}

export enum DIALOG_CLOSE {
  BETTING_RELOAD = 'BETTING_RELOAD',
  BETTING_DEAL_RELOAD = 'BETTING_DEAL_RELOAD',
  ODDS_RELOAD = 'ODDS_RELOAD'
}