export enum DIALOG_NAME {
  START_LOADING = 'START_LOADING',
  ODDS_CANCEL = 'ODDS_CANCEL',
  INSTALL_METAMASK = 'INSTALL_METAMASK',
  IS_NETWORK = 'IS_NETWORK',
  STORE_BETTING = 'STORE_BETTING',
  BETTING_SHARING = 'BETTING_SHARING',
  SHARING_SOCIAL = 'SHARING_SOCIAL',
  CLAIM_STAKE = 'CLAIM_STAKE'
}

export enum DIALOG_CLOSE {
  BETTING_RELOAD = 'BETTING_RELOAD',
  BETTING_DEAL_RELOAD = 'BETTING_DEAL_RELOAD',
  ODDS_RELOAD = 'ODDS_RELOAD'
}
