export var USER_TYPE_OPEN;
(function (USER_TYPE_OPEN) {
    USER_TYPE_OPEN["ODDS_ALL"] = "all bet";
    USER_TYPE_OPEN["ODDS_SETTLED"] = "settled";
    USER_TYPE_OPEN["ODDS_OPEN"] = "open";
    USER_TYPE_OPEN["ODDS_CANCELLED"] = "cancelled";
})(USER_TYPE_OPEN || (USER_TYPE_OPEN = {}));
export var USER_TYPE_FINISHED;
(function (USER_TYPE_FINISHED) {
    USER_TYPE_FINISHED["ODDS_ALL"] = "all bet";
    USER_TYPE_FINISHED["ODDS_WON"] = "won";
    USER_TYPE_FINISHED["ODDS_LOST"] = "lost";
    USER_TYPE_FINISHED["ODDS_REFUNDED"] = "refunded";
})(USER_TYPE_FINISHED || (USER_TYPE_FINISHED = {}));
export var ODDS_STATUS;
(function (ODDS_STATUS) {
    ODDS_STATUS[ODDS_STATUS["ODDS_OPEN"] = 0] = "ODDS_OPEN";
    ODDS_STATUS[ODDS_STATUS["ODDS_SETTLED"] = 1] = "ODDS_SETTLED";
    ODDS_STATUS[ODDS_STATUS["ODDS_CANCELLED"] = 2] = "ODDS_CANCELLED";
    ODDS_STATUS[ODDS_STATUS["ODDS_REFUNDED"] = 3] = "ODDS_REFUNDED";
    ODDS_STATUS[ODDS_STATUS["ODDS_DONE"] = 4] = "ODDS_DONE";
})(ODDS_STATUS || (ODDS_STATUS = {}));
export var ODDS_TYPE;
(function (ODDS_TYPE) {
    ODDS_TYPE["ZERO"] = "0";
    ODDS_TYPE["UNDER_QUARTER"] = "+0.25";
    ODDS_TYPE["UNDER_THREE_A_FOURTHS"] = "+0.75";
    ODDS_TYPE["UNDER_HALF"] = "+0.5";
    ODDS_TYPE["UNDER_ONE"] = "+1";
    ODDS_TYPE["UNDER_ONE_AND_QUARTER"] = "+1.25";
    ODDS_TYPE["UNDER_ONE_AND_THREE_A_FOURTHS"] = "+1.75";
    ODDS_TYPE["UNDER_ONE_AND_HALF"] = "+1.5";
    ODDS_TYPE["UNDER_TWO"] = "+2";
    ODDS_TYPE["OVER_QUARTER"] = "-0.25";
    ODDS_TYPE["OVER_THREE_A_FOURTHS"] = "-0.75";
    ODDS_TYPE["OVER_HALF"] = "-0.5";
    ODDS_TYPE["OVER_ONE"] = "-1";
    ODDS_TYPE["OVER_ONE_AND_QUARTER"] = "-1.25";
    ODDS_TYPE["OVER_ONE_AND_THREE_A_FOURTHS"] = "-1.75";
    ODDS_TYPE["OVER_ONE_AND_HALF"] = "-1.5";
    ODDS_TYPE["OVER_TWO"] = "-2";
})(ODDS_TYPE || (ODDS_TYPE = {}));
//# sourceMappingURL=odds.js.map